[pytest]
addopts = -p no:opik

filterwarnings =
    ignore::DeprecationWarning:litellm.*
    ignore::DeprecationWarning:urllib3.*
    ignore:.*PydanticDeprecatedSince20.*:DeprecationWarning
    ignore:.*strict.*parameter.*:DeprecationWarning
